theme: jekyll-theme-minimal
title: "Kenneth A. Flagg: Statistical Practitioner"
description: "Independent statistical consultant with experience in environmentalstatistics, survey analysis, design of experiments, enterprise data science, and cloud computing."
