theme: jekyll-theme-minimal
title: "Kenny Flagg: Statistics Practitioner"
description: "Independent statistical consultant with experience in environmental statistics, survey analysis, design of experiments, enterprise data science, and cloud computing."
