theme: jekyll-theme-alembic
title: "Kenny Flagg: Data Scientist and Statistics Practitioner"
description: "I think about data. My work has touched upon environmental statistics, study design and analysis, sales process automation, cloud computing, enterprise data engineering, MLOps, and teaching/mentoring."
